module hw.xfree86.drivers.video.modesetting.driver;
@nogc nothrow:
extern(C): __gshared:

private template HasVersion(string versionId) {
	mixin("version("~versionId~") {enum HasVersion = true;} else {enum HasVersion = false;}");
}
import core.stdc.config: c_long, c_ulong;
/*
 * Copyright 2008 Tungsten Graphics, Inc., Cedar Park, Texas.
 * Copyright 2011 Dave Airlie
 * Copyright 2019 NVIDIA CORPORATION
 * All Rights Reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sub license, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice (including the
 * next paragraph) shall be included in all copies or substantial portions
 * of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.
 * IN NO EVENT SHALL TUNGSTEN GRAPHICS AND/OR ITS SUPPLIERS BE LIABLE FOR
 * ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 *
 * Original Author: Alan Hourihane <alanh@tungstengraphics.com>
 * Rewrite: Dave Airlie <airlied@redhat.com>
 * Additional contributors:
 *   Aaron Plattner <aplattner@nvidia.com>
 *
 */

import build.dix_config;
import include.glamor;
import hw.xfree86.drivers.video.modesetting.dri2;
import dix.pixmap;

import core.stdc.errno;
import core.stdc.stdlib;
import core.sys.posix.unistd;
import core.sys.posix.fcntl;
//import externs.X11.extensions._randr;
// //import externs.X11.extensions.Xv;
import include.xf86xv;

import config.hotplug_priv;
import dix.dix_priv;
import include.edid;
import include.xorgVersion;
import mi.mi_priv;
import pageflip;

import include.xf86;
import include.xf86Priv;
import include.xf86_OSproc;;
import include.compiler;
import include.xf86Pci;
import mi.mipointer;
import include.mipointrst;
import mi.micmap;
import include.fb;
import include.xf86i2c;
import include.xf86Crtc;
import include.miscstruct;
import include.dixstruct;
import build.xlibre_server;
import xf86pciBus;

// import xf86xv;
import externs.libdrm;
// import build.xorg_config;
static if(XSERVER_PLATFORM_BUS){
import xf86platformBus_priv;
}
static if(XSERVER_LIBPCIACCESS){
import externs.pciaccess;
}

version (SEATD_LIBSEAT) {
import seatd_libseat;
}

import hw.xfree86.drivers.video.modesetting.driver;
import hw.xfree86.drivers.video.modesetting.drmmode_bo;
// import hw.xfree86.drivers.video.modesetting
// import externs.libdrm;;
import include.shadow;
import hw.xfree86.common.xf86Helper;
import include.mipointer;
import hw.xfree86.drivers.video.modesetting.drmmode_display;
import externs.libdrm;;
import xf86Option;
import externs.gnu;
import include.inputstr;
import include.optionstr;
import xf86fbBus;
import include.pixmapstr;
import hw.xfree86.drivers.video.modesetting.present;
struct ms_async_flip_priv {
    Bool async_flip;
    Bool async_flip_modifiers;
};
import mi.miscrinit;
import os.log;
import include.xf86Cursor;
import core.sys.posix.stdlib;
import mi.midispcur;
import hw.xfree86.drivers.video.modesetting.vblank;
import hw.xfree86.modes.xf86Crtc;
import hw.xfree86.loader.loader;
import randr.randr;
import xf86Globals;

alias CARD32 = x11.Xmd.CARD32;

alias SetupFnPtr = extern(C) Bool function(ScreenPtr) @nogc nothrow;
alias AddFnPtr = extern(C) Bool function(ScreenPtr, PixmapPtr, ShadowUpdateProc, ShadowWindowProc,
            int, void *)  @nogc nothrow;
alias RemoveFnPtr = extern(C) void function(ScreenPtr, PixmapPtr) @nogc nothrow;
alias Update32to24FnPtr = extern(C) void function(ScreenPtr, shadowBufPtr) @nogc nothrow;
alias UpdatePackedFnPtr = extern(C) void function(ScreenPtr, shadowBufPtr) @nogc nothrow;

alias uint32_t = core.stdc.stdint.uint32_t;
alias uint64_t = core.stdc.stdint.uint64_t;
alias uint16_t = core.stdc.stdint.uint16_t;

alias void function (modesettingPtr ms,
                                         uint64_t frame,
                                         uint64_t usec,
                                         void *data) ms_pageflip_handler_proc;

alias void function (modesettingPtr ms, void *data)ms_pageflip_abort_proc;
enum MS_LOGLEVEL_DEBUG = 4;
enum string modesettingPTR(string p)= `(cast(modesettingPtr)((`~p~`).driverPrivate))`;
/**
 * A tracked handler for an event that will hopefully be generated by
 * the kernel, and what to do when it is encountered.
 */
struct ms_drm_queue {
    xorg_list list;
    xf86CrtcPtr crtc;
    uint32_t seq;
    uint64_t msc;
    void *data;
    ScrnInfoPtr scrn;
    ms_drm_handler_proc handler;
    ms_drm_abort_proc abort;
    Bool kernel_queued;
    Bool aborted;
};

// struct gbm_device;
// struct gbm_bo;
// struct drmModeClip;
struct _modesettingRec {
    int fd;
    Bool fd_passed;

    int Chipset;
    EntityInfoPtr pEnt;

    Bool noAccel;
    CloseScreenProcPtr CloseScreen;
    CreateWindowProcPtr CreateWindow;
    x_server_generation_t SaveGeneration;

    ScreenBlockHandlerProcPtr BlockHandler;
    miPointerSpriteFuncPtr SpriteFuncs;
    void *driver;

    drmmode_rec drmmode;

    drmEventContext event_context;

    /**
     * Page flipping stuff.
     *  @{
     */
    Bool atomic_modeset_capable;
    Bool atomic_modeset;
    Bool pending_modeset;
    /** @} */

    DamagePtr damage;
    Bool dirty_enabled;

    uint32_t cursor_image_width;
    uint32_t cursor_image_height;

    Bool has_queue_sequence;
    Bool tried_queue_sequence;

    Bool kms_has_modifiers;

    /* VRR support */
    Bool vrr_support;
    WindowPtr flip_window;

    Bool is_connector_vrr_capable;
    uint32_t connector_prop_id;

    /* shadow API */
    struct Shadow {
        Bool function(ScreenPtr) @nogc nothrow Setup;
        Bool function(ScreenPtr, PixmapPtr, ShadowUpdateProc, ShadowWindowProc,
                    int, void *)  @nogc nothrow Add;
        void function(ScreenPtr, PixmapPtr) @nogc nothrow Remove;
        void function(ScreenPtr, shadowBufPtr) @nogc nothrow Update32to24;
        void function(ScreenPtr, shadowBufPtr) @nogc nothrow UpdatePacked;
    } 
    Shadow shadow;

static if( GLAMOR) {
    /* glamor API */
    struct _GLAMOR{
        Bool function(PixmapPtr, int, CARD16, CARD16, CARD16,
                                    CARD8, CARD8) @nogc nothrow  back_pixmap_from_fd;
        void function(ScreenPtr) @nogc nothrow block_handler;
        void function(PixmapPtr) @nogc nothrow clear_pixmap;
        Bool function(PixmapPtr, int, int) @nogc nothrow egl_create_textured_pixmap;
        Bool function(PixmapPtr ,
                                                       gbm_bo *,
                                                       Bool) @nogc nothrow egl_create_textured_pixmap_from_gbm_bo;
        void function(PixmapPtr, PixmapPtr) @nogc nothrow egl_exchange_buffers;
        gbm_device *function(ScreenPtr) @nogc nothrow egl_get_gbm_device;
        Bool function(ScrnInfoPtr, int, int*, int) @nogc nothrow egl_init2;
        void function(ScreenPtr) @nogc nothrow finish;
        gbm_bo *function(ScreenPtr, PixmapPtr) @nogc nothrow gbm_bo_from_pixmap;
        Bool function(ScreenPtr, uint) @nogc nothrow init;
        int function(PixmapPtr, CARD16 *, CARD32 *) @nogc nothrow name_from_pixmap;
        void function(ScreenPtr ,
                                            GetDrawableModifiersFuncPtr) @nogc nothrow set_drawable_modifiers_func;
        int function(ScreenPtr, PixmapPtr, CARD16 * ,
                                        CARD32 *) @nogc nothrow shareable_fd_from_pixmap;
        Bool function(ScreenPtr) @nogc nothrow supports_pixmap_import_export;
        XF86VideoAdaptorPtr function(ScreenPtr, int) @nogc nothrow xv_init;
        const(char*) function(ScreenPtr) @nogc nothrow egl_get_driver_name;
    }
    _GLAMOR glamor;
}
} 
alias GetDrawableModifiersFuncPtr = Bool function(DrawablePtr draw,
                                             uint32_t format,
                                             uint32_t *num_modifiers,
                                             uint64_t **modifiers);
struct ms_vrr_priv {
    Bool variable_refresh;
};

alias modesettingRec = _modesettingRec;
alias modesettingPtr = modesettingRec*;

alias ms_drm_handler_proc = void function(uint64_t frame,
                                    uint64_t usec,
                                    void *data);

alias ms_drm_abort_proc = void function(void *data);

alias ms_queue_flag = int;
enum : ms_queue_flag {
    MS_QUEUE_ABSOLUTE = 0,
    MS_QUEUE_RELATIVE = 1,
    MS_QUEUE_NEXT_ON_MISS = 2
};

enum {
    OPTION_SW_CURSOR,
    OPTION_CURSOR_SIZE,
    OPTION_DEVICE_PATH,
    OPTION_SHADOW_FB,
    OPTION_ACCEL_METHOD,
    OPTION_PAGEFLIP,
    OPTION_ZAPHOD_HEADS,
    OPTION_DOUBLE_SHADOW,
    OPTION_ATOMIC,
    OPTION_VARIABLE_REFRESH,
    OPTION_USE_GAMMA_LUT,
    OPTION_ASYNC_FLIP_SECONDARIES,
    OPTION_TEARFREE,
}

struct modesettingEntRec
{
    int fd;
    int fd_ref;
    x_server_generation_t fd_wakeup_registered; /* server generation for which fd has been registered for wakeup handling */
    int fd_wakeup_ref;
    uint assigned_crtcs;
} 
alias modesettingEntPtr = modesettingEntRec*;

private const(OptionInfoRec)* AvailableOptions(int chipid, int busid);








static if(XSERVER_LIBPCIACCESS){

}


static if(XSERVER_LIBPCIACCESS){
private const(pci_id_match)[3] ms_device_match = [
    {
     PCI_MATCH_ANY, PCI_MATCH_ANY, PCI_MATCH_ANY, PCI_MATCH_ANY,
     0x00030000, 0x00ff0000, 0},

    {0, 0, 0},
];
}

static if(XSERVER_PLATFORM_BUS){} else {
struct xf86_platform_device;
}

static if(XSERVER_PLATFORM_BUS){

}

export DriverRec modesetting;

static this()
{
    modesetting.driverVersion = 1;
    modesetting.driverName = "modesetting";

    modesetting.Identify = &Identify;
    modesetting.Probe = &Probe;
    modesetting.AvailableOptions = &AvailableOptions;

    modesetting.module_ = null;
    modesetting.refCount = 0;

    modesetting.driverFunc = &ms_driver_func;

    version (XSERVER_LIBPCIACCESS)
    {
        modesetting.supported_devices = ms_device_match;
        modesetting.PciProbe = &ms_pci_probe;
    }
    else
    {
        modesetting.supported_devices = null;
        modesetting.PciProbe = null;
    }

    version (XSERVER_PLATFORM_BUS)
    {
        modesetting.platformProbe = &ms_platform_probe;
    }
}

private SymTabRec[2] Chipsets = [
    {0, "kms"},
    {-1, null}
];

private const(OptionInfoRec)[14] Options = [
    {OPTION_SW_CURSOR, "SWcursor", OPTV_BOOLEAN, {0}, FALSE},
    {OPTION_CURSOR_SIZE, "CursorSize", OPTV_STRING, {0}, FALSE},
    {OPTION_DEVICE_PATH, "kmsdev", OPTV_STRING, {0}, FALSE},
    {OPTION_SHADOW_FB, "ShadowFB", OPTV_BOOLEAN, {0}, FALSE},
    {OPTION_ACCEL_METHOD, "AccelMethod", OPTV_STRING, {0}, FALSE},
    {OPTION_PAGEFLIP, "PageFlip", OPTV_BOOLEAN, {0}, FALSE},
    {OPTION_ZAPHOD_HEADS, "ZaphodHeads", OPTV_STRING, {0}, FALSE},
    {OPTION_DOUBLE_SHADOW, "DoubleShadow", OPTV_BOOLEAN, {0}, FALSE},
    {OPTION_ATOMIC, "Atomic", OPTV_BOOLEAN, {0}, FALSE},
    {OPTION_VARIABLE_REFRESH, "VariableRefresh", OPTV_BOOLEAN, {0}, FALSE},
    {OPTION_USE_GAMMA_LUT, "UseGammaLUT", OPTV_BOOLEAN, {0}, FALSE},
    {OPTION_ASYNC_FLIP_SECONDARIES, "AsyncFlipSecondaries", OPTV_BOOLEAN, {0}, FALSE},
    {OPTION_TEARFREE, "TearFree", OPTV_BOOLEAN, {0}, FALSE},
    {-1, null, OPTV_NONE, {0}, FALSE}
];

int ms_entity_index = -1;

private DevPrivateKeyRec asyncFlipPrivateKeyRec;

// private MODULESETUPPROTO Setup;

private XF86ModuleVersionInfo VersRecMS = {
    modname: "modesetting",
    vendor: MODULEVENDORSTRING,
    _modinfo1_: MODINFOSTRING1,
    _modinfo2_: MODINFOSTRING2,
    xf86version: mixin(XORG_VERSION_CURRENT),
    majorversion: mixin(XORG_VERSION_MAJOR),
    minorversion: mixin(XORG_VERSION_MINOR),
    patchlevel: mixin(XORG_VERSION_PATCH),
    abiclass: ABI_CLASS_VIDEODRV,
    abiversion: ABI_VIDEODRV_VERSION,
    moduleclass: MOD_CLASS_VIDEODRV,
};

export XF86ModuleData modesettingModuleData = {
    vers: &VersRecMS,
    setup: &Setup
};

private void* Setup(void* module_, void* opts, int* errmaj, int* errmin)
{
    static Bool setupDone = 0;

    /* This module should be loaded only once, but check to be sure.
     */
    if (!setupDone) {
        setupDone = 1;
        xf86AddDriver(&modesetting, module_, HaveDriverFuncs);

        /*
         * The return value must be non-NULL on success even though there
         * is no TearDownProc.
         */
        return cast(void*) 1;
    }
    else {
        if (errmaj)
            *errmaj = LDR_ONCEONLY;
        return null;
    }
}

private void Identify(int flags)
{
    xf86PrintChipsets("modesetting", "Driver for Modesetting Kernel Drivers",
                      Chipsets.ptr);
}

modesettingEntPtr ms_ent_priv(ScrnInfoPtr scrn)
{
    DevUnion* pPriv = void;
    modesettingPtr ms = mixin(modesettingPTR!("scrn"));
    pPriv = xf86GetEntityPrivate(ms.pEnt.index,
                                 ms_entity_index);
    return cast(modesettingEntRec*)pPriv.ptr;
}

private int get_passed_fd()
{
    if (xf86DRMMasterFd >= 0) {
        xf86DrvMsg(-1, X_INFO, "Using passed DRM master file descriptor %d\n", xf86DRMMasterFd);
        return dup(xf86DRMMasterFd);
    }
    return -1;
}

private int ms_try_open(const(char)* dev)
{
    int fd = -1;

    if (!dev) {
        return -1;
    }

    fd = open(dev, O_RDWR | O_CLOEXEC, 0);
    if (fd >= 0) {
        return fd;
    }

version (SEATD_LIBSEAT) {
    //pragma(mangle, mixin(cFixer!(__MODULE__, __LINE__)))
    return seatd_libseat_open_graphics(dev);
} else {
    return -1;
}
}

private int open_hw(const(char)* dev)
{
    int fd = void;

    if ((fd = get_passed_fd()) != -1)
        return fd;

    if (dev){
        fd = ms_try_open(dev);
    } else {
        dev = getenv("KMSDEVICE");
        if ((null == dev) || ((fd = ms_try_open(dev)) < 0)) {
            int i = void;
            char[16] buf = "/dev/dri/cardxx";

            for (i = 0; i < 32; i++) {
                sprintf(buf.ptr, "/dev/dri/card%d", i);

                if ((fd = ms_try_open(buf.ptr)) >= 0) {
                    ulong check_dumb = 0;

                    if (drmGetCap(fd, DRM_CAP_DUMB_BUFFER, &check_dumb) >= 0 && check_dumb) {
                        break;
                    }

                    close(fd);
                    fd = -1;
                }
            }
        }
    }
    if (fd == -1) {
        xf86DrvMsg(-1, X_ERROR, "open %s: %s\n", dev, strerror(errno));
    } else if (fd < -1) {
        xf86DrvMsg(-1, X_ERROR, "open %s: failed to open, tried seatd_libseat_open_graphics and opening node directly",dev);
	fd = -1;
    }

    return fd;
}

private int check_outputs(int fd, int* count)
{
    drmModeResPtr res = drmModeGetResources(fd);
    int ret = void;

    if (!res)
        return FALSE;

    if (count)
        *count = res.count_connectors;

    ret = res.count_connectors > 0;
static if (HasVersion!"GLAMOR" && HasVersion!"GBM_HAVE_BO_USE_LINEAR") {
    if (ret == FALSE) {
        ulong value = 0;
        if (drmGetCap(fd, DRM_CAP_PRIME, &value) == 0 &&
                (value & DRM_PRIME_CAP_EXPORT))
            ret = TRUE;
    }
}
    drmModeFreeResources(res);
    return ret;
}

private Bool probe_hw(const(char)* dev, xf86_platform_device* platform_dev)
{
    int fd = void;

version (XF86_PDEV_SERVER_FD) {
    if (platform_dev && (platform_dev.flags & XF86_PDEV_SERVER_FD)) {
        fd = xf86_platform_device_odev_attributes(platform_dev).fd;
        if (fd == -1)
            return FALSE;
        return check_outputs(fd, null);
    }
}

    fd = open_hw(dev);
    if (fd != -1) {
        int ret = check_outputs(fd, null);

        close(fd);
        return ret;
    }
    return FALSE;
}

static if(XSERVER_LIBPCIACCESS){
char* ms_DRICreatePCIBusID(const(pci_device)* dev)
{
    char* busID = void;

    if (asprintf(&busID, "pci:%04x:%02x:%02x.%d",
                 dev.domain, dev.bus, dev.dev, dev.func) == -1)
        return null;

    return busID;
}
}

private Bool probe_hw_pci(const(char)* dev, pci_device* pdev)
{
    int ret = FALSE, fd = open_hw(dev);
    char* id = void, devid = void;
    drmSetVersion sv = void;

    if (fd == -1)
        return FALSE;

    sv.drm_di_major = 1;
    sv.drm_di_minor = 4;
    sv.drm_dd_major = -1;
    sv.drm_dd_minor = -1;
    if (drmSetInterfaceVersion(fd, &sv)) {
        close(fd);
        return FALSE;
    }

    id = drmGetBusid(fd);
    devid = ms_DRICreatePCIBusID(pdev);

    if (id && devid && !strcmp(id, devid))
        ret = check_outputs(fd, null);

    close(fd);
    free(id);
    free(devid);
    return ret;
}

private const(OptionInfoRec)* AvailableOptions(int chipid, int busid)
{
    return Options.ptr;
}

private Bool ms_driver_func(ScrnInfoPtr scrn, xorgDriverFuncOp op, void* data)
{
    xorgHWFlags* flag = void;

    switch (op) {
    case GET_REQUIRED_HW_INTERFACES:
        flag = cast(xorgHWFlags*) (cast(CARD32*) data);
        (*flag) = 0;
        return TRUE;
    case SUPPORTS_SERVER_FDS:
        return TRUE;
    default:
        return FALSE;
    }
}

private void ms_setup_scrn_hooks(ScrnInfoPtr scrn)
{
    scrn.driverVersion = 1;
    scrn.driverName = "modesetting";
    scrn.name = "modeset";

    scrn.Probe = null;
    scrn.PreInit = &PreInit;
    scrn.ScreenInit = &ScreenInit;
    scrn.SwitchMode = &SwitchMode;
    scrn.AdjustFrame = &AdjustFrame;
    scrn.EnterVT = &EnterVT;
    scrn.LeaveVT = &LeaveVT;
    scrn.FreeScreen = &FreeScreen;
    scrn.ValidMode = &ValidMode;
}

private void ms_setup_entity(ScrnInfoPtr scrn, int entity_num)
{
    DevUnion* pPriv = void;

    xf86SetEntitySharable(entity_num);

    if (ms_entity_index == -1)
        ms_entity_index = xf86AllocateEntityPrivateIndex();

    pPriv = xf86GetEntityPrivate(entity_num,
                                 ms_entity_index);

    xf86SetEntityInstanceForScreen(scrn, entity_num, xf86GetNumEntityInstances(entity_num) - 1);

    if (!pPriv.ptr)
        pPriv.ptr = XNFcallocarray(1, modesettingEntRec.sizeof);
}

static if(XSERVER_LIBPCIACCESS){
private Bool ms_pci_probe(DriverPtr driver, int entity_num, pci_device* dev, intptr_t match_data)
{
    ScrnInfoPtr scrn = null;

    scrn = xf86ConfigPciEntity(scrn, 0, entity_num, null,
                               null, null, null, null, null);
    if (scrn) {
        const(char)* devpath = void;
        GDevPtr devSection = xf86GetDevFromEntity(scrn.entityList[0],
                                                  scrn.entityInstanceList[0]);

        devpath = xf86FindOptionValue(cast(_InputOption*)devSection.options, "kmsdev");
        if (probe_hw_pci(devpath, dev)) {
            ms_setup_scrn_hooks(scrn);

            xf86DrvMsg(scrn.scrnIndex, X_CONFIG,
                       "claimed PCI slot %d@%d:%d:%d\n",
                       dev.bus, dev.domain, dev.dev, dev.func);
            xf86DrvMsg(scrn.scrnIndex, X_INFO,
                       "using %s\n", devpath ? devpath : "default device");

            ms_setup_entity(scrn, entity_num);
        }
        else
            scrn = null;
    }
    return scrn !is null;
}
}

static if(XSERVER_PLATFORM_BUS){
private Bool ms_platform_probe(DriverPtr driver, int entity_num, int flags, xf86_platform_device* dev, intptr_t match_data)
{
    ScrnInfoPtr scrn = null;
    const(char)* path = xf86_platform_device_odev_attributes(dev).path;
    int scr_flags = 0;

    if (flags & PLATFORM_PROBE_GPU_SCREEN)
        scr_flags = XF86_ALLOCATE_GPU_SCREEN;

    if (probe_hw(path, dev)) {
        scrn = xf86AllocateScreen(driver, scr_flags);
        if (xf86IsEntitySharable(entity_num))
            xf86SetEntityShared(entity_num);
        xf86AddEntityToScreen(scrn, entity_num);

        ms_setup_scrn_hooks(scrn);

        xf86DrvMsg(scrn.scrnIndex, X_INFO,
                   "using drv %s\n", path ? path : "default device");

        ms_setup_entity(scrn, entity_num);
    }

    return scrn !is null;
}
}

private Bool Probe(DriverPtr drv, int flags)
{
    int i = void, numDevSections = void;
    GDevPtr* devSections = void;
    Bool foundScreen = FALSE;

    /* For now, just bail out for PROBE_DETECT. */
    if (flags & PROBE_DETECT)
        return FALSE;

    /*
     * Find the config file Device sections that match this
     * driver, and return if there are none.
     */
    if ((numDevSections = xf86MatchDevice("modesetting", &devSections)) <= 0) {
        return FALSE;
    }

    for (i = 0; i < numDevSections; i++) {
        int entity_num = -1;
        ScrnInfoPtr scrn = null;
        const(char)* dev = xf86FindOptionValue(cast(_InputOption*)devSections[i].options, "kmsdev");

        if (probe_hw(dev, null)) {
            entity_num = xf86ClaimFbSlot(drv, 0, devSections[i], TRUE);
        }

        if (entity_num != -1) {
            scrn = xf86ConfigFbEntity(scrn, 0, entity_num, null, null, null, null);
        }

        if (scrn) {
            foundScreen = TRUE;
            ms_setup_scrn_hooks(scrn);
            scrn.Probe = &Probe;

            xf86DrvMsg(scrn.scrnIndex, X_INFO,
                       "using %s\n", dev ? dev : "default device");
            ms_setup_entity(scrn, entity_num);
        }
    }

    free(devSections);

    return foundScreen;
}

private Bool GetRec(ScrnInfoPtr pScrn)
{
    if (pScrn.driverPrivate)
        return TRUE;

    pScrn.driverPrivate = XNFcallocarray(1, modesettingRec.sizeof);

    return TRUE;
}

private int rotate_clip(PixmapPtr pixmap, xf86CrtcPtr crtc, BoxPtr rect, drmModeClip* clip, Rotation rotation, int x, int y)
{
    int w = void, h = void;
    int x1 = void, y1 = void, x2 = void, y2 = void;

    if (rotation == RR_Rotate_90 || rotation == RR_Rotate_270) {
        /* width and height are swapped if rotated 90 or 270 degrees */
        w = pixmap.drawable.height;
        h = pixmap.drawable.width;
    } else {
        w = pixmap.drawable.width;
        h = pixmap.drawable.height;
    }

    /* check if the given rect covers any area in FB of the crtc */
    if (rect.x2 > crtc.x && rect.x1 < crtc.x + w &&
        rect.y2 > crtc.y && rect.y1 < crtc.y + h) {
        /* new coordinate of the partial rect on the crtc area
         * + x/y offsets in the framebuffer */
        x1 = max(rect.x1 - crtc.x, 0) + x;
        y1 = max(rect.y1 - crtc.y, 0) + y;
        x2 = min(rect.x2 - crtc.x, w) + x;
        y2 = min(rect.y2 - crtc.y, h) + y;

        /* coordinate transposing/inversion and offset adjustment */
        if (rotation == RR_Rotate_90) {
            clip.x1 = cast(ushort)(y1);
            clip.y1 = cast(ushort)(w - x2);
            clip.x2 = cast(ushort)(y2);
            clip.y2 = cast(ushort)(w - x1);
        } else if (rotation == RR_Rotate_180) {
            clip.x1 = cast(ushort)(w - x2);
            clip.y1 = cast(ushort)(h - y2);
            clip.x2 = cast(ushort)(w - x1);
            clip.y2 = cast(ushort)(h - y1);
        } else if (rotation == RR_Rotate_270) {
            clip.x1 = cast(ushort)(h - y2);
            clip.y1 = cast(ushort)(x1);
            clip.x2 = cast(ushort)(h - y1);
            clip.y2 = cast(ushort)(x2);
        } else {
            clip.x1 = cast(ushort)(x1);
            clip.y1 = cast(ushort)(y1);
            clip.x2 = cast(ushort)(x2);
            clip.y2 = cast(ushort)(y2);
        }
    } else {
        return -1;
    }

    return 0;
}

private int dispatch_damages(ScrnInfoPtr scrn, xf86CrtcPtr crtc, RegionPtr dirty, PixmapPtr pixmap, DamagePtr damage, int fb_id, int x, int y)
{
    modesettingPtr ms = mixin(modesettingPTR!("scrn"));
    uint num_cliprects = REGION_NUM_RECTS(dirty);
    int ret = 0;

    if (!ms.dirty_enabled)
        return 0;

    if (num_cliprects) {
        drmModeClip* clip = cast(drmModeClip*) calloc(num_cliprects, drmModeClip.sizeof);
        BoxPtr rect = REGION_RECTS(dirty);
        int i = void;
        int c = 0;

        if (!clip)
            return -ENOMEM;

        /* Create clips for the given rects in case the rect covers any
         * area in the FB.
         */
        for (i = 0; i < num_cliprects; i++, rect++) {
            if (rotate_clip(pixmap, crtc, rect, &clip[c], crtc.rotation, x, y) < 0)
                continue;

            c++;
        }

        if (!c)
            return 0;

        /* TODO query connector property to see if this is needed */
        ret = drmModeDirtyFB(ms.fd, fb_id, clip, c);

        /* if we're swamping it with work, try one at a time */
        if (ret == -EINVAL) {
            for (i = 0; i < c; i++) {
                if ((ret = drmModeDirtyFB(ms.fd, fb_id, &clip[i], 1)) < 0)
                    break;
            }
        }

        if (ret == -EINVAL || ret == -ENOSYS) {
            xf86DrvMsg(scrn.scrnIndex, X_INFO,
                       "Disabling kernel dirty updates, not required.\n");
            ms.dirty_enabled = FALSE;
        }

        free(clip);
    }
    return ret;
}

private int dispatch_dirty_region(ScrnInfoPtr scrn, xf86CrtcPtr crtc, PixmapPtr pixmap, DamagePtr damage, int fb_id, int x, int y)
{
    return dispatch_damages(scrn, crtc, DamageRegion(damage),
                            pixmap, damage, fb_id, x, y);
}

private void ms_tearfree_update_damages(ScreenPtr pScreen)
{
    ScrnInfoPtr scrn = xf86ScreenToScrn(pScreen);
    xf86CrtcConfigPtr xf86_config = mixin(XF86_CRTC_CONFIG_PTR!("scrn"));
    modesettingPtr ms = mixin(modesettingPTR!("scrn"));
    RegionPtr dirty = DamageRegion(ms.damage);
    int c = void, i = void;

    if (RegionNil(dirty))
        return;

    for (c = 0; c < xf86_config.num_crtc; c++) {
        xf86CrtcPtr crtc = xf86_config.crtc[c];
        drmmode_crtc_private_ptr drmmode_crtc = cast(drmmode_crtc_private_ptr)crtc.driver_private;
        drmmode_tearfree_ptr trf = &drmmode_crtc.tearfree;
        RegionRec region = void;

        /* Compute how much of the damage intersects with this CRTC */
        RegionInit(&region, &crtc.bounds, 0);
        RegionIntersect(&region, &region, dirty);

        if (trf.buf[0].px) {
            for (i = 0; i < mixin(ARRAY_SIZE!("trf.buf")); i++)
                RegionUnion(&trf.buf[i].dmg, &trf.buf[i].dmg, &region);
        } else {
            /* Just notify the kernel of the damages if TearFree isn't used */
            dispatch_damages(scrn, crtc, &region,
                             pScreen.GetScreenPixmap(pScreen),
                             null, ms.drmmode.fb_id, 0, 0);
        }
    }
    DamageEmpty(ms.damage);
}

private void ms_tearfree_do_flips(ScreenPtr pScreen)
{
static if (GLAMOR) {
    ScrnInfoPtr scrn = xf86ScreenToScrn(pScreen);
    xf86CrtcConfigPtr xf86_config = mixin(XF86_CRTC_CONFIG_PTR!("scrn"));
    modesettingPtr ms = mixin(modesettingPTR!("scrn"));
    int c = void;

    if (!ms.drmmode.tearfree_enable)
        return;

    for (c = 0; c < xf86_config.num_crtc; c++) {
        xf86CrtcPtr crtc = xf86_config.crtc[c];
        drmmode_crtc_private_ptr drmmode_crtc = cast(drmmode_crtc_private_ptr) crtc.driver_private;
        drmmode_tearfree_ptr trf = &drmmode_crtc.tearfree;

        if (!ms_tearfree_is_active_on_crtc(crtc)) {
            /* Notify any lingering DRI clients waiting for a flip to finish */
            ms_tearfree_dri_abort_all(crtc);
            continue;
        }

        /* Skip if the last flip is still pending, a DRI client is flipping, or
         * there isn't any damage on the front buffer.
         */
        if (trf.flip_seq || ms.drmmode.dri2_flipping ||
            ms.drmmode.present_flipping ||
            RegionNil(&trf.buf[trf.back_idx ^ 1].dmg))
            continue;

        /* Flip. If it fails, notify the kernel of the front buffer damages */
        if (ms_do_tearfree_flip(pScreen, crtc)) {
            dispatch_damages(scrn, crtc, &trf.buf[trf.back_idx ^ 1].dmg,
                             trf.buf[trf.back_idx ^ 1].px, null,
                             trf.buf[trf.back_idx ^ 1].fb_id, 0, 0);
            RegionEmpty(&trf.buf[trf.back_idx ^ 1].dmg);
        }
    }
}
}

private void dispatch_dirty(ScreenPtr pScreen)
{
    ScrnInfoPtr scrn = xf86ScreenToScrn(pScreen);
    xf86CrtcConfigPtr xf86_config = mixin(XF86_CRTC_CONFIG_PTR!("scrn"));
    modesettingPtr ms = mixin(modesettingPTR!("scrn"));
    PixmapPtr pixmap = pScreen.GetScreenPixmap(pScreen);
    uint fb_id = void;
    int ret = void, c = void, x = void, y = void;

    for (c = 0; c < xf86_config.num_crtc; c++) {
        xf86CrtcPtr crtc = xf86_config.crtc[c];
        PixmapPtr pmap = void;

        drmmode_crtc_private_ptr drmmode_crtc = cast(drmmode_crtc_private_ptr)crtc.driver_private;

        if (!drmmode_crtc)
            continue;

        drmmode_crtc_get_fb_id(crtc, &fb_id, &x, &y);

        if (crtc.rotatedPixmap)
            pmap = crtc.rotatedPixmap;
        else
            pmap = pixmap;

        ret = dispatch_dirty_region(scrn, crtc, pmap, ms.damage, fb_id, x, y);
        if (ret == -EINVAL || ret == -ENOSYS) {
            DamageUnregister(ms.damage);
            DamageDestroy(ms.damage);
            ms.damage = null;
            return;
        }
    }

    DamageEmpty(ms.damage);
}

private void dispatch_dirty_pixmap(ScrnInfoPtr scrn, xf86CrtcPtr crtc, PixmapPtr ppix)
{
    modesettingPtr ms = mixin(modesettingPTR!("scrn"));
    msPixmapPrivPtr ppriv = mixin(msGetPixmapPriv!("&ms.drmmode", "ppix"));
    DamagePtr damage = ppriv.secondary_damage;
    int fb_id = ppriv.fb_id;

    dispatch_dirty_region(scrn, crtc, ppix, damage, fb_id, 0, 0);
    if (damage)
        DamageEmpty(damage);
}

private void dispatch_secondary_dirty(ScreenPtr pScreen)
{
    ScrnInfoPtr scrn = xf86ScreenToScrn(pScreen);
    xf86CrtcConfigPtr xf86_config = mixin(XF86_CRTC_CONFIG_PTR!("scrn"));
    int c = void;

    for (c = 0; c < xf86_config.num_crtc; c++) {
        xf86CrtcPtr crtc = xf86_config.crtc[c];
        drmmode_crtc_private_ptr drmmode_crtc = cast(drmmode_crtc_private_ptr)crtc.driver_private;

        if (!drmmode_crtc)
            continue;

        if (drmmode_crtc.prime_pixmap)
            dispatch_dirty_pixmap(scrn, crtc, drmmode_crtc.prime_pixmap);
        if (drmmode_crtc.prime_pixmap_back)
            dispatch_dirty_pixmap(scrn, crtc, drmmode_crtc.prime_pixmap_back);
    }
}

private void redisplay_dirty(ScreenPtr screen, PixmapDirtyUpdatePtr dirty, int* timeout)
{
    RegionRec pixregion = void;

    PixmapRegionInit(&pixregion, dirty.secondary_dst);
    DamageRegionAppend(&dirty.secondary_dst.drawable, &pixregion);
    PixmapSyncDirtyHelper(dirty);

    if (!screen.isGPU) {
static if (GLAMOR) {
        modesettingPtr ms = mixin(modesettingPTR!("xf86ScreenToScrn(screen)"));
        /*
         * When copying from the primary framebuffer to the shared pixmap,
         * we must ensure the copy is complete before the secondary starts a
         * copy to its own framebuffer (some secondarys scanout directly from
         * the shared pixmap, but not all).
         */
        if (ms.drmmode.glamor_gbm)
            ms.glamor.finish(screen);
}
        /* Ensure the secondary processes the damage immediately */
        if (timeout)
            *timeout = 0;
    }

    DamageRegionProcessPending(&dirty.secondary_dst.drawable);
    RegionUninit(&pixregion);
}

private void ms_dirty_update(ScreenPtr screen, int* timeout)
{
    modesettingPtr ms = mixin(modesettingPTR!("xf86ScreenToScrn(screen)"));

    RegionPtr region = void;
    PixmapDirtyUpdatePtr ent = void;

    if (xorg_list_is_empty(&screen.pixmap_dirty_list))
        return;

    mixin(xorg_list_for_each_entry!("ent", "&screen.pixmap_dirty_list", "ent", q{
        region = DamageRegion(ent.damage);
        if (RegionNotEmpty(region)) {
            if (!screen.isGPU) {
                   msPixmapPrivPtr ppriv = mixin(msGetPixmapPriv!("&ms.drmmode", "ent.secondary_dst.primary_pixmap"));

                if (ppriv.notify_on_damage) {
                    ppriv.notify_on_damage = FALSE;

                    ent.secondary_dst.drawable.pScreen.
                        SharedPixmapNotifyDamage(ent.secondary_dst);
                }

                /* Requested manual updating */
                if (ppriv.defer_dirty_update)
                    continue;
            }

            redisplay_dirty(screen, ent, timeout);
            DamageEmpty(ent.damage);
        }
    }));
}

private PixmapDirtyUpdatePtr ms_dirty_get_ent(ScreenPtr screen, PixmapPtr secondary_dst)
{
    PixmapDirtyUpdatePtr ent = void;

    if (xorg_list_is_empty(&screen.pixmap_dirty_list))
        return null;

    mixin(xorg_list_for_each_entry!("ent", "&screen.pixmap_dirty_list", "ent", q{
        if (ent.secondary_dst == secondary_dst)
            return ent;
    }));

    return null;
}

private void msBlockHandler(ScreenPtr pScreen, void* timeout)
{
    modesettingPtr ms = mixin(modesettingPTR!("xf86ScreenToScrn(pScreen)"));

    pScreen.BlockHandler = ms.BlockHandler;
    pScreen.BlockHandler(pScreen, timeout);
    ms.BlockHandler = pScreen.BlockHandler;
    pScreen.BlockHandler = &msBlockHandler;
    if (pScreen.isGPU && !ms.drmmode.reverse_prime_offload_mode)
        dispatch_secondary_dirty(pScreen);
    else if (ms.drmmode.tearfree_enable)
        ms_tearfree_update_damages(pScreen);
    else if (ms.dirty_enabled)
        dispatch_dirty(pScreen);

    ms_dirty_update(pScreen, cast(int*)timeout);
    ms_tearfree_do_flips(pScreen);
}

private void msBlockHandler_oneshot(ScreenPtr pScreen, void* pTimeout)
{
    ScrnInfoPtr pScrn = xf86ScreenToScrn(pScreen);
    modesettingPtr ms = mixin(modesettingPTR!("pScrn"));

    msBlockHandler(pScreen, pTimeout);

    drmmode_set_desired_modes(pScrn, &ms.drmmode, TRUE, FALSE);
}

Bool ms_window_has_variable_refresh(modesettingPtr ms, WindowPtr win) {
        ms_vrr_priv* priv = cast(ms_vrr_priv*)dixLookupPrivate(&win.devPrivates, &ms.drmmode.vrrPrivateKeyRec);
        return priv.variable_refresh;
}

private void msSetWindowVRRMode(WindowPtr window, WindowVRRMode mode)
{
    Bool variable_refresh = (mode == WINDOW_VRR_ENABLED);
    ScrnInfoPtr scrn = xf86ScreenToScrn(window.drawable.pScreen);
    modesettingPtr ms = mixin(modesettingPTR!("scrn"));

    ms_vrr_priv* priv = cast(ms_vrr_priv*)dixLookupPrivate(&window.devPrivates,
                                                &ms.drmmode.vrrPrivateKeyRec);
    priv.variable_refresh = variable_refresh;

    if (ms.flip_window == window && ms.drmmode.present_flipping)
        ms_present_set_screen_vrr(scrn, variable_refresh);
}


Bool ms_window_has_async_flip(WindowPtr win)
{
    ms_async_flip_priv* priv = cast(ms_async_flip_priv*)dixLookupPrivate(&win.devPrivates,
                                                       &asyncFlipPrivateKeyRec);

    return priv.async_flip;
}

void ms_window_update_async_flip(WindowPtr win, Bool async_flip)
{
    ms_async_flip_priv* priv = cast(ms_async_flip_priv*)dixLookupPrivate(&win.devPrivates,
                                                       &asyncFlipPrivateKeyRec);

    priv.async_flip = async_flip;
}

Bool ms_window_has_async_flip_modifiers(WindowPtr win)
{
    ms_async_flip_priv* priv = cast(ms_async_flip_priv*)dixLookupPrivate(&win.devPrivates,
                                                       &asyncFlipPrivateKeyRec);

    return priv.async_flip_modifiers;
}

void ms_window_update_async_flip_modifiers(WindowPtr win, Bool async_flip)
{
    ms_async_flip_priv* priv = cast(ms_async_flip_priv*)dixLookupPrivate(&win.devPrivates,
                                                       &asyncFlipPrivateKeyRec);

    priv.async_flip_modifiers = async_flip;
}

private void FreeScreen(ScrnInfoPtr pScrn)
{
    modesettingPtr ms = void;

    if (!pScrn)
        return;

    ms = mixin(modesettingPTR!("pScrn"));
    if (!ms)
        return;

    if (ms.fd > 0) {
        modesettingEntPtr ms_ent = void;
        int ret = void;

        ms_ent = ms_ent_priv(pScrn);
        ms_ent.fd_ref--;
        if (!ms_ent.fd_ref) {
            if (ms.pEnt.location.type == BUS_PCI)
                ret = drmClose(ms.fd);
            else {
version (XF86_PDEV_SERVER_FD) {
                if (!(ms.pEnt.location.type == BUS_PLATFORM &&
                      (ms.pEnt.location.id.plat.flags & XF86_PDEV_SERVER_FD)))
                    ret = close(ms.fd);
}
else {
                    ret = close(ms.fd);

}
            }
            cast(void) ret;
            ms_ent.fd = 0;
        }
    }
    pScrn.driverPrivate = null;
    free(ms.drmmode.Options);
    free(ms);

}

static if (GLAMOR) {

private Bool load_glamor(ScrnInfoPtr pScrn)
{
    void* mod = xf86LoadSubModule(pScrn, GLAMOR_EGL_MODULE_NAME);
    modesettingPtr ms = mixin(modesettingPTR!("pScrn"));

    if (!mod)
        return FALSE;

    ms.glamor.back_pixmap_from_fd = cast(typeof(ms.glamor.back_pixmap_from_fd))LoaderSymbolFromModule(mod, "glamor_back_pixmap_from_fd");
    ms.glamor.block_handler = cast(typeof(ms.glamor.block_handler))LoaderSymbolFromModule(mod, "glamor_block_handler");
    ms.glamor.clear_pixmap = cast(typeof(ms.glamor.clear_pixmap))LoaderSymbolFromModule(mod, "glamor_clear_pixmap");
    ms.glamor.egl_create_textured_pixmap = cast(typeof(ms.glamor.egl_create_textured_pixmap))LoaderSymbolFromModule(mod, "glamor_egl_create_textured_pixmap");
    ms.glamor.egl_create_textured_pixmap_from_gbm_bo = cast(typeof(ms.glamor.egl_create_textured_pixmap_from_gbm_bo))LoaderSymbolFromModule(mod, "glamor_egl_create_textured_pixmap_from_gbm_bo");
    ms.glamor.egl_exchange_buffers = cast(typeof(ms.glamor.egl_exchange_buffers))LoaderSymbolFromModule(mod, "glamor_egl_exchange_buffers");
    ms.glamor.egl_get_gbm_device = cast(typeof(ms.glamor.egl_get_gbm_device))LoaderSymbolFromModule(mod, "glamor_egl_get_gbm_device");
    ms.glamor.egl_init2 = cast(typeof(ms.glamor.egl_init2))LoaderSymbolFromModule(mod, "glamor_egl_init2");
    ms.glamor.finish = cast(typeof(ms.glamor.finish))LoaderSymbolFromModule(mod, "glamor_finish");
    ms.glamor.gbm_bo_from_pixmap = cast(typeof(ms.glamor.gbm_bo_from_pixmap))LoaderSymbolFromModule(mod, "glamor_gbm_bo_from_pixmap");
    ms.glamor.init = cast(typeof(ms.glamor.init))LoaderSymbolFromModule(mod, "glamor_init");
    ms.glamor.name_from_pixmap = cast(typeof(ms.glamor.name_from_pixmap))LoaderSymbolFromModule(mod, "glamor_name_from_pixmap");
    ms.glamor.set_drawable_modifiers_func = cast(typeof(ms.glamor.set_drawable_modifiers_func))LoaderSymbolFromModule(mod, "glamor_set_drawable_modifiers_func");
    ms.glamor.shareable_fd_from_pixmap = cast(typeof(ms.glamor.shareable_fd_from_pixmap))LoaderSymbolFromModule(mod, "glamor_shareable_fd_from_pixmap");
    ms.glamor.supports_pixmap_import_export = cast(typeof(ms.glamor.supports_pixmap_import_export))LoaderSymbolFromModule(mod, "glamor_supports_pixmap_import_export");
    ms.glamor.xv_init = cast(typeof(ms.glamor.xv_init))LoaderSymbolFromModule(mod, "glamor_xv_init");
    ms.glamor.egl_get_driver_name = cast(typeof(ms.glamor.egl_get_driver_name))LoaderSymbolFromModule(mod, "glamor_egl_get_driver_name");

    return TRUE;
}

}

private void try_enable_glamor(ScrnInfoPtr pScrn)
{
    modesettingPtr ms = mixin(modesettingPTR!("pScrn"));
    const(char)* accel_method_str = xf86GetOptValString(ms.drmmode.Options,
                                                       OPTION_ACCEL_METHOD);
    Bool do_glamor = (!accel_method_str ||
                      strcmp(accel_method_str, "glamor") == 0);

    ms.drmmode.glamor = FALSE;
    ms.drmmode.glamor_gbm = FALSE;

static if (GLAMOR) {
    if (ms.drmmode.force_24_32) {
        xf86DrvMsg(pScrn.scrnIndex, X_CONFIG, "Cannot use glamor with 24bpp packed fb\n");
        return;
    }

    if (!do_glamor) {
        xf86DrvMsg(pScrn.scrnIndex, X_CONFIG, "glamor disabled\n");
        return;
    }

    if (load_glamor(pScrn)) {
        int caps = GLAMOR_EGL_CAP_NONE;
        if (ms.glamor.egl_init2(pScrn, ms.fd, &caps, 0)) {
            ms.drmmode.glamor_gbm = !!(caps & GLAMOR_EGL_CAP_TEXTURE_GBM_BO);
            xf86DrvMsg(pScrn.scrnIndex, X_INFO, "glamor initialized\n");
            ms.drmmode.glamor = TRUE;
        } else {
            xf86DrvMsg(pScrn.scrnIndex, X_INFO,
                       "glamor initialization failed\n");
        }
    } else {
        xf86DrvMsg(pScrn.scrnIndex, X_ERROR,
                   "Failed to load glamor module.\n");
    }
} else {
    if (do_glamor) {
        xf86DrvMsg(pScrn.scrnIndex, X_INFO,
                   "No glamor support in the X Server\n");
    }
}
}

private Bool msShouldDoubleShadow(ScrnInfoPtr pScrn, modesettingPtr ms)
{
    Bool ret = FALSE, asked = void;
    int from = void;
    drmVersionPtr v = void;

    if (!ms.drmmode.shadow_enable)
        return FALSE;

    if ((v = drmGetVersion(ms.fd)) !is null) {
        if (!strcmp(v.name, "mgag200") ||
            !strcmp(v.name, "ast")) /* XXX || rn50 */
            ret = TRUE;

        drmFreeVersion(v);
    }
    else
        xf86DrvMsg(pScrn.scrnIndex, X_ERROR,
                   "Failed to query DRM version.\n");

    asked = xf86GetOptValBool(ms.drmmode.Options, OPTION_DOUBLE_SHADOW, &ret);

    if (asked)
        from = X_CONFIG;
    else
        from = X_INFO;

    xf86DrvMsg(pScrn.scrnIndex, cast(MessageType)from,
               "Double-buffered shadow updates: %s\n", ret ? "on".ptr : "off".ptr);

    return ret;
}

private Bool ms_get_drm_master_fd(ScrnInfoPtr pScrn)
{
    auto ms = mixin(modesettingPTR!("pScrn"));
    auto ms_ent = ms_ent_priv(pScrn);

    static if (XSERVER_PLATFORM_BUS ||
               XSERVER_LIBPCIACCESS)
    {
        auto pEnt = ms.pEnt;
    }

    if (ms_ent.fd != 0) {
        xf86DrvMsg(pScrn.scrnIndex,
                   X_INFO,
                   " reusing fd for second head\n");

        ms.fd = ms_ent.fd;
        ms_ent.fd_ref++;

        return TRUE;
    }

    ms.fd_passed = FALSE;

    if ((ms.fd = get_passed_fd()) >= 0) {
        ms.fd_passed = TRUE;
        return TRUE;
    }

    static if (XSERVER_PLATFORM_BUS)
{
    if (pEnt.location.type == BUS_PLATFORM) {

        static if (XF86_PDEV_SERVER_FD)
        {
            if ((pEnt.location.id.plat.flags &
                 XF86_PDEV_SERVER_FD) != 0)
            {
                ms.fd =
                    xf86_platform_device_odev_attributes(
                        pEnt.location.id.plat).fd;
            }
            else
            {
                auto path =
                    xf86_platform_device_odev_attributes(
                        pEnt.location.id.plat).path;

                ms.fd = open_hw(path);
            }
        }
        else
        {
            auto path =
                xf86_platform_device_odev_attributes(
                    pEnt.location.id.plat).path;

            ms.fd = open_hw(path);
        }
    }
    else
    {
        static if (XSERVER_LIBPCIACCESS)
        {
            if (pEnt.location.type == BUS_PCI) {

                char* BusID = null;
                pci_device* PciInfo = null;

                PciInfo = xf86GetPciInfoForEntity(ms.pEnt.index);

                if (PciInfo !is null) {

                    BusID = ms_DRICreatePCIBusID(PciInfo);

                    if (BusID !is null) {
                        ms.fd = drmOpen(null, BusID);
                        free(BusID);
                    }
                }
            }
            else
            {
                const(char)* devicename =
                    xf86FindOptionValue(
                        cast(_InputOption*)ms.pEnt.device.options,
                        "kmsdev".ptr);

                ms.fd = open_hw(devicename);
            }
        }
        else
        {
            const(char)* devicename =
                xf86FindOptionValue(
                    ms.pEnt.device.options,
                    "kmsdev");

            ms.fd = open_hw(devicename);
        }
    }
}

    if (ms.fd < 0)
        return FALSE;

    ms_ent.fd = ms.fd;
    ms_ent.fd_ref = 1;

    return TRUE;
}

private Bool PreInit(ScrnInfoPtr pScrn, int flags)
{
    modesettingPtr ms = void;
    rgb defaultWeight = { 0, 0, 0 };
    EntityInfoPtr pEnt = void;
    ulong value = 0;
    int ret = void;
    int bppflags = void, connector_count = void;
    int defaultdepth = void, defaultbpp = void;

    if (pScrn.numEntities != 1)
        return FALSE;

    if (flags & PROBE_DETECT) {
        return FALSE;
    }

    /* Allocate driverPrivate */
    if (!GetRec(pScrn))
        return FALSE;

    pEnt = xf86GetEntityInfo(pScrn.entityList[0]);

    ms = mixin(modesettingPTR!("pScrn"));
    ms.SaveGeneration = -1;
    ms.pEnt = pEnt;
    ms.drmmode.is_secondary = FALSE;
    pScrn.displayWidth = 640;  /* default it */

    if (xf86IsEntityShared(pScrn.entityList[0])) {
        if (xf86IsPrimInitDone(pScrn.entityList[0]))
            ms.drmmode.is_secondary = TRUE;
        else
            xf86SetPrimInitDone(pScrn.entityList[0]);
    }

    pScrn.monitor = pScrn.confScreen.monitor;
    pScrn.progClock = TRUE;
    pScrn.rgbBits = 8;

    if (!ms_get_drm_master_fd(pScrn))
        return FALSE;
    ms.drmmode.fd = ms.fd;

    if (!check_outputs(ms.fd, &connector_count))
        return FALSE;

    drmmode_get_default_bpp(pScrn, &ms.drmmode, &defaultdepth, &defaultbpp);
    if (defaultdepth == 24 && defaultbpp == 24) {
        ms.drmmode.force_24_32 = TRUE;
        ms.drmmode.kbpp = 24;
        xf86DrvMsg(pScrn.scrnIndex, X_INFO,
                   "Using 24bpp hw front buffer with 32bpp shadow\n");
        defaultbpp = 32;
    } else {
        ms.drmmode.kbpp = 0;
    }
    bppflags = PreferConvert24to32 | SupportConvert24to32 | Support32bppFb;

    if (!xf86SetDepthBpp
        (pScrn, defaultdepth, defaultdepth, defaultbpp, bppflags))
        return FALSE;

    switch (pScrn.depth) {
    case 15:
    case 16:
    case 24:
    case 30:
        break;
    default:
        xf86DrvMsg(pScrn.scrnIndex, X_ERROR,
                   "Given depth (%d) is not supported by the driver\n",
                   pScrn.depth);
        return FALSE;
    }
    xf86PrintDepthBpp(pScrn);
    if (!ms.drmmode.kbpp)
        ms.drmmode.kbpp = pScrn.bitsPerPixel;

    /* Process the options */
    xf86CollectOptions(pScrn, null);
    if (((ms.drmmode.Options = cast(OptionInfoPtr) calloc(1, Options.sizeof)) is null))
        return FALSE;
    memcpy(ms.drmmode.Options, Options.ptr, Options.sizeof);
    xf86ProcessOptions(pScrn.scrnIndex, cast(_InputOption*)pScrn.options, ms.drmmode.Options);

    if (!xf86SetWeight(pScrn, defaultWeight, defaultWeight))
        return FALSE;
    if (!xf86SetDefaultVisual(pScrn, -1))
        return FALSE;

    if (xf86ReturnOptValBool(ms.drmmode.Options, OPTION_SW_CURSOR, FALSE)) {
        ms.drmmode.sw_cursor = TRUE;
    }

    try_enable_glamor(pScrn);

    if (!ms.drmmode.glamor_gbm) {
        Bool prefer_shadow = TRUE;

        if (ms.drmmode.force_24_32) {
            prefer_shadow = TRUE;
            ms.drmmode.shadow_enable = TRUE;
        } else {
            ret = drmGetCap(ms.fd, DRM_CAP_DUMB_PREFER_SHADOW, &value);
            if (!ret) {
                prefer_shadow = !!value;
            }

            ms.drmmode.shadow_enable =
                xf86ReturnOptValBool(ms.drmmode.Options, OPTION_SHADOW_FB,
                                     prefer_shadow);
        }

        xf86DrvMsg(pScrn.scrnIndex, X_INFO,
                   "ShadowFB: preferred %s, enabled %s\n",
                   prefer_shadow ? "YES".ptr : "NO".ptr,
                   ms.drmmode.force_24_32 ? "FORCE".ptr :
                   ms.drmmode.shadow_enable ? "YES".ptr : "NO".ptr);

        ms.drmmode.shadow_enable2 = msShouldDoubleShadow(pScrn, ms);
    } else {
        if (!pScrn.is_gpu) {
            MessageType from = xf86GetOptValBool(ms.drmmode.Options, OPTION_VARIABLE_REFRESH,
                                                 &ms.vrr_support) ? X_CONFIG : X_DEFAULT;
            xf86DrvMsg(pScrn.scrnIndex, from, "VariableRefresh: %sabled\n",
                       ms.vrr_support ? "en".ptr : "dis".ptr);

            ms.drmmode.async_flip_secondaries = FALSE;
            from = xf86GetOptValBool(ms.drmmode.Options, OPTION_ASYNC_FLIP_SECONDARIES,
                                     &ms.drmmode.async_flip_secondaries) ? X_CONFIG : X_DEFAULT;
            xf86DrvMsg(pScrn.scrnIndex, from, "AsyncFlipSecondaries: %sabled\n",
                       ms.drmmode.async_flip_secondaries ? "en".ptr : "dis".ptr);
        }
    }

    ms.drmmode.pageflip =
        xf86ReturnOptValBool(ms.drmmode.Options, OPTION_PAGEFLIP, TRUE);

    pScrn.capabilities = 0;
    ret = drmGetCap(ms.fd, DRM_CAP_PRIME, &value);
    if (ret == 0) {
        if (connector_count && (value & DRM_PRIME_CAP_IMPORT)) {
            pScrn.capabilities |= RR_Capability_SinkOutput;
            if (ms.drmmode.glamor_gbm)
                pScrn.capabilities |= RR_Capability_SinkOffload;
        }
static if (HasVersion!"GLAMOR" && HasVersion!"GBM_HAVE_BO_USE_LINEAR") {
        if (value & DRM_PRIME_CAP_EXPORT && ms.drmmode.glamor_gbm)
            pScrn.capabilities |= RR_Capability_SourceOutput | RR_Capability_SourceOffload;
}
    }

    /*
     * Use "atomic modesetting disable" request to detect if the kms driver is
     * atomic capable, regardless if we will actually use atomic modesetting.
     * This is effectively a no-op, we only care about the return status code.
     */
    ret = drmSetClientCap(ms.fd, DRM_CLIENT_CAP_ATOMIC, 0);
    ms.atomic_modeset_capable = (ret == 0);

    if (xf86ReturnOptValBool(ms.drmmode.Options, OPTION_ATOMIC, FALSE)) {
        ret = drmSetClientCap(ms.fd, DRM_CLIENT_CAP_ATOMIC, 2);
        ms.atomic_modeset = (ret == 0);
        if (!ms.atomic_modeset)
            xf86DrvMsg(pScrn.scrnIndex, X_WARNING, "Atomic modesetting not supported\n");
    } else {
        ms.atomic_modeset = FALSE;
    }
    xf86DrvMsg(pScrn.scrnIndex, X_INFO,
               "Atomic modesetting %sabled\n", ms.atomic_modeset ? "en".ptr : "dis".ptr);

    /* TearFree requires glamor and, if PageFlip is enabled, universal planes */
    if (xf86ReturnOptValBool(ms.drmmode.Options, OPTION_TEARFREE, TRUE)) {
        if (pScrn.is_gpu) {
            xf86DrvMsg(pScrn.scrnIndex, X_WARNING,
                       "TearFree cannot synchronize PRIME; use 'PRIME Synchronization' instead\n");
        } else if (ms.drmmode.glamor_gbm) {
            /* Atomic modesetting implicitly enables universal planes */
            if (!ms.drmmode.pageflip || ms.atomic_modeset ||
                !drmSetClientCap(ms.fd, DRM_CLIENT_CAP_UNIVERSAL_PLANES, 1)) {
                ms.drmmode.tearfree_enable = TRUE;
                xf86DrvMsg(pScrn.scrnIndex, X_INFO, "TearFree: enabled\n");
            } else {
                xf86DrvMsg(pScrn.scrnIndex, X_WARNING,
                           "TearFree requires either universal planes, or setting 'Option \"PageFlip\" \"off\"'\n");
            }
        } else {
            xf86DrvMsg(pScrn.scrnIndex, X_WARNING,
                       "TearFree requires Glamor acceleration\n");
        }
    }

    ms.kms_has_modifiers = FALSE;
    ret = drmGetCap(ms.fd, DRM_CAP_ADDFB2_MODIFIERS, &value);
    if (ret == 0 && value != 0)
        ms.kms_has_modifiers = TRUE;

    if (drmmode_pre_init(pScrn, &ms.drmmode, pScrn.bitsPerPixel / 8) == FALSE) {
        xf86DrvMsg(pScrn.scrnIndex, X_ERROR, "KMS setup failed\n");
        goto fail;
    }

    /*
     * If the driver can do gamma correction, it should call xf86SetGamma() here.
     */
    {
        Gamma zeros = { 0.0, 0.0, 0.0 };

        if (!xf86SetGamma(pScrn, zeros)) {
            return FALSE;
        }
    }

    if (!(pScrn.is_gpu && connector_count == 0) && pScrn.modes is null) {
        xf86DrvMsg(pScrn.scrnIndex, X_ERROR, "No modes.\n");
        return FALSE;
    }

    pScrn.currentMode = pScrn.modes;

    /* Set display resolution */
    xf86SetDpi(pScrn, 0, 0);

    /* Load the required sub modules */
    if (!xf86LoadSubModule(pScrn, "fb")) {
        return FALSE;
    }

    if (ms.drmmode.shadow_enable) {
        void* mod = xf86LoadSubModule(pScrn, "shadow");

        if (!mod)
            return FALSE;

        ms.shadow.Setup        = cast(SetupFnPtr)LoaderSymbolFromModule(mod, "shadowSetup");
        ms.shadow.Add          = cast(AddFnPtr)LoaderSymbolFromModule(mod, "shadowAdd");
        ms.shadow.Remove       = cast(RemoveFnPtr)LoaderSymbolFromModule(mod, "shadowRemove");
        ms.shadow.Update32to24 = cast(Update32to24FnPtr)LoaderSymbolFromModule(mod, "shadowUpdate32to24");
        ms.shadow.UpdatePacked = cast(UpdatePackedFnPtr)LoaderSymbolFromModule(mod, "shadowUpdatePacked");
    }

    return TRUE;
 fail:
    return FALSE;
}

private void* msShadowWindow(ScreenPtr screen, CARD32 row, CARD32 offset, int mode, CARD32* size, void* closure)
{
    ScrnInfoPtr pScrn = xf86ScreenToScrn(screen);
    modesettingPtr ms = mixin(modesettingPTR!("pScrn"));
    int stride = void;

    stride = (pScrn.displayWidth * ms.drmmode.kbpp) / 8;
    *size = stride;

    return (cast(ubyte*) gbm_bo_get_map(ms.drmmode.front_bo) + row * stride + offset);
}

/* somewhat arbitrary tile size, in pixels */
enum TILE = 16;

private int msUpdateIntersect(modesettingPtr ms, shadowBufPtr pBuf, BoxPtr box, xRectangle* prect)
{
    int i = void, dirty = 0, stride = pBuf.pPixmap.devKind, cpp = ms.drmmode.cpp;
    int width = (box.x2 - box.x1) * cpp;
    ubyte* old = void, new_ = void;

    old = cast(ubyte*)ms.drmmode.shadow_fb2;
    old += (box.y1 * stride) + (box.x1 * cpp);
    new_ = cast(ubyte*)ms.drmmode.shadow_fb;
    new_ += (box.y1 * stride) + (box.x1 * cpp);

    for (i = box.y2 - box.y1 - 1; i >= 0; i--) {
        ubyte* o = old + i * stride, n = new_ + i * stride;
        if (memcmp(o, n, width) != 0) {
            dirty = 1;
            memcpy(o, n, width);
        }
    }

    if (dirty) {
        prect.x = box.x1;
        prect.y = box.y1;
        prect.width = cast(ushort)(box.x2 - box.x1);
        prect.height = cast(ushort)(box.y2 - box.y1);
    }

    return dirty;
}

private void msUpdatePacked(ScreenPtr pScreen, shadowBufPtr pBuf)
{
    ScrnInfoPtr pScrn = xf86ScreenToScrn(pScreen);
    modesettingPtr ms = mixin(modesettingPTR!("pScrn"));
    Bool use_3224 = ms.drmmode.force_24_32 && pScrn.bitsPerPixel == 32;

    if (ms.drmmode.shadow_enable2 && ms.drmmode.shadow_fb2) do {
        RegionPtr damage = DamageRegion(pBuf.pDamage), tiles = void;
        BoxPtr extents = RegionExtents(damage);
        xRectangle* prect = void;
        int nrects = void;
        int i = void, j = void, tx1 = void, tx2 = void, ty1 = void, ty2 = void;

        tx1 = extents.x1 / TILE;
        tx2 = (extents.x2 + TILE - 1) / TILE;
        ty1 = extents.y1 / TILE;
        ty2 = (extents.y2 + TILE - 1) / TILE;

        nrects = (tx2 - tx1) * (ty2 - ty1);
        if (((prect = cast(xRectangle*) calloc(nrects, xRectangle.sizeof)) is null))
            break;

        nrects = 0;
        for (j = ty2 - 1; j >= ty1; j--) {
            for (i = tx2 - 1; i >= tx1; i--) {
                BoxRec box = void;

                box.x1 = cast(short)max(i * TILE, extents.x1);
                box.y1 = cast(short)max(j * TILE, extents.y1);
                box.x2 = cast(short)min((i+1) * TILE, extents.x2);
                box.y2 = cast(short)min((j+1) * TILE, extents.y2);

                if (RegionContainsRect(damage, &box) != rgnOUT) {
                    if (msUpdateIntersect(ms, pBuf, &box, prect + nrects)) {
                        nrects++;
                    }
                }
            }
        }

        tiles = RegionFromRects(nrects, prect, CT_NONE);
        RegionIntersect(damage, damage, tiles);
        RegionDestroy(tiles);
        free(prect);
    } while (0);

    if (use_3224)
        ms.shadow.Update32to24(pScreen, pBuf);
    else
        ms.shadow.UpdatePacked(pScreen, pBuf);
}

private Bool msEnableSharedPixmapFlipping(RRCrtcPtr crtc, PixmapPtr front, PixmapPtr back)
{
    ScreenPtr screen = crtc.pScreen;
    ScrnInfoPtr scrn = xf86ScreenToScrn(screen);
    modesettingPtr ms = mixin(modesettingPTR!("scrn"));
    xf86CrtcPtr xf86Crtc = cast(xf86CrtcPtr)crtc.devPrivate;

    if (!xf86Crtc)
        return FALSE;

    /* Not supported if we can't flip */
    if (!ms.drmmode.pageflip)
        return FALSE;

    /* Not currently supported with reverse PRIME */
    if (ms.drmmode.reverse_prime_offload_mode)
        return FALSE;

static if(XSERVER_PLATFORM_BUS){
    if (ms.pEnt.location.type == BUS_PLATFORM) {
        const(char)* syspath = xf86_platform_device_odev_attributes(ms.pEnt.location.id.plat).
            syspath;

        /* Not supported for devices using USB transport due to misbehaved
         * vblank events */
        if (syspath && strstr(syspath, "usb"))
            return FALSE;

        /* EVDI uses USB transport but is platform device, not usb.
         * Exclude it explicitly. */
        if (syspath && strstr(syspath, "evdi"))
            return FALSE;
    }
}

    return drmmode_EnableSharedPixmapFlipping(xf86Crtc, &ms.drmmode,
                                              front, back);
}

private void msDisableSharedPixmapFlipping(RRCrtcPtr crtc)
{
    ScreenPtr screen = crtc.pScreen;
    ScrnInfoPtr scrn = xf86ScreenToScrn(screen);
    modesettingPtr ms = mixin(modesettingPTR!("scrn"));
    xf86CrtcPtr xf86Crtc = cast(xf86CrtcPtr)crtc.devPrivate;

    if (xf86Crtc)
        drmmode_DisableSharedPixmapFlipping(xf86Crtc, &ms.drmmode);
}

private Bool msStartFlippingPixmapTracking(RRCrtcPtr crtc, DrawablePtr src, PixmapPtr secondary_dst1, PixmapPtr secondary_dst2, int x, int y, int dst_x, int dst_y, Rotation rotation)
{
    ScreenPtr pScreen = src.pScreen;
    modesettingPtr ms = mixin(modesettingPTR!("xf86ScreenToScrn(pScreen)"));

    msPixmapPrivPtr ppriv1 = mixin(msGetPixmapPriv!("&ms.drmmode", "secondary_dst1.primary_pixmap")), ppriv2 = mixin(msGetPixmapPriv!("&ms.drmmode", "secondary_dst2.primary_pixmap"));

    if (!PixmapStartDirtyTracking(src, secondary_dst1, x, y,
                                  dst_x, dst_y, rotation)) {
        return FALSE;
    }

    if (!PixmapStartDirtyTracking(src, secondary_dst2, x, y,
                                  dst_x, dst_y, rotation)) {
        PixmapStopDirtyTracking(src, secondary_dst1);
        return FALSE;
    }

    ppriv1.secondary_src = src;
    ppriv2.secondary_src = src;

    ppriv1.dirty = ms_dirty_get_ent(pScreen, secondary_dst1);
    ppriv2.dirty = ms_dirty_get_ent(pScreen, secondary_dst2);

    ppriv1.defer_dirty_update = TRUE;
    ppriv2.defer_dirty_update = TRUE;

    return TRUE;
}

private Bool msPresentSharedPixmap(PixmapPtr secondary_dst)
{
    ScreenPtr pScreen = secondary_dst.primary_pixmap.drawable.pScreen;
    modesettingPtr ms = mixin(modesettingPTR!("xf86ScreenToScrn(pScreen)"));

    msPixmapPrivPtr ppriv = mixin(msGetPixmapPriv!("&ms.drmmode", "secondary_dst.primary_pixmap"));

    RegionPtr region = DamageRegion(ppriv.dirty.damage);

    if (RegionNotEmpty(region)) {
        redisplay_dirty(ppriv.secondary_src.pScreen, ppriv.dirty, null);
        DamageEmpty(ppriv.dirty.damage);

        return TRUE;
    }

    return FALSE;
}

private Bool msStopFlippingPixmapTracking(DrawablePtr src, PixmapPtr secondary_dst1, PixmapPtr secondary_dst2)
{
    ScreenPtr pScreen = src.pScreen;
    modesettingPtr ms = mixin(modesettingPTR!("xf86ScreenToScrn(pScreen)"));

    msPixmapPrivPtr ppriv1 = mixin(msGetPixmapPriv!("&ms.drmmode", "secondary_dst1.primary_pixmap")), ppriv2 = mixin(msGetPixmapPriv!("&ms.drmmode", "secondary_dst2.primary_pixmap"));

    Bool ret = TRUE;

    ret &= PixmapStopDirtyTracking(src, secondary_dst1);
    ret &= PixmapStopDirtyTracking(src, secondary_dst2);

    if (ret) {
        ppriv1.secondary_src = null;
        ppriv2.secondary_src = null;

        ppriv1.dirty = null;
        ppriv2.dirty = null;

        ppriv1.defer_dirty_update = FALSE;
        ppriv2.defer_dirty_update = FALSE;
    }

    return ret;
}

private Bool modesetCreateScreenResources(ScreenPtr pScreen)
{
    ScrnInfoPtr pScrn = xf86ScreenToScrn(pScreen);
    modesettingPtr ms = mixin(modesettingPTR!("pScrn"));
    PixmapPtr rootPixmap = void;
    void* pixels = null;
    int err = void;

    Bool ret = miCreateScreenResources(pScreen);

    if (!drmmode_set_desired_modes(pScrn, &ms.drmmode, pScrn.is_gpu, FALSE))
        return FALSE;

    if (!drmmode_glamor_handle_new_screen_pixmap(&ms.drmmode))
        return FALSE;

    drmmode_uevent_init(pScrn, &ms.drmmode);

    if (!ms.drmmode.glamor_gbm) {
        pixels = gbm_bo_get_map(ms.drmmode.front_bo);
    }

    rootPixmap = pScreen.GetScreenPixmap(pScreen);

    if (ms.drmmode.shadow_enable)
        pixels = ms.drmmode.shadow_fb;

    if (ms.drmmode.shadow_enable2) {
        ms.drmmode.shadow_fb2 = calloc(1, pScrn.displayWidth * pScrn.virtualY * ((pScrn.bitsPerPixel + 7) >> 3));
        if (!ms.drmmode.shadow_fb2)
            ms.drmmode.shadow_enable2 = FALSE;
    }

    if (!pScreen.ModifyPixmapHeader(rootPixmap, -1, -1, -1, -1, -1, pixels))
        FatalError("Couldn't adjust screen pixmap\n");

    if (ms.drmmode.shadow_enable) {
        if (!ms.shadow.Add(pScreen, rootPixmap, &msUpdatePacked, &msShadowWindow,
                            0, null))
            return FALSE;
    }

    err = drmModeDirtyFB(ms.fd, ms.drmmode.fb_id, null, 0);

    if ((err != -EINVAL && err != -ENOSYS) || ms.drmmode.tearfree_enable) {
        ms.damage = DamageCreate(null, null, DamageReportNone, TRUE,
                                  pScreen, rootPixmap);

        if (ms.damage) {
            DamageRegister(&rootPixmap.drawable, ms.damage);
            ms.dirty_enabled = err != -EINVAL && err != -ENOSYS;
            xf86DrvMsg(pScrn.scrnIndex, X_INFO, "Damage tracking initialized\n");
        }
        else {
            xf86DrvMsg(pScrn.scrnIndex, X_ERROR,
                       "Failed to create screen damage record\n");
            return FALSE;
        }
    }

    if (dixPrivateKeyRegistered(rrPrivKey)) {
        rrScrPrivPtr pScrPriv = mixin(rrGetScrPriv!("pScreen"));

        pScrPriv.rrEnableSharedPixmapFlipping = &msEnableSharedPixmapFlipping;
        pScrPriv.rrDisableSharedPixmapFlipping = &msDisableSharedPixmapFlipping;

        pScrPriv.rrStartFlippingPixmapTracking = &msStartFlippingPixmapTracking;
    }

    if (ms.vrr_support &&
        !dixRegisterPrivateKey(&ms.drmmode.vrrPrivateKeyRec,
                               PRIVATE_WINDOW,
                               ms_vrr_priv.sizeof))
            return FALSE;

    if (!dixRegisterPrivateKey(&asyncFlipPrivateKeyRec,
                               PRIVATE_WINDOW,
                               ms_async_flip_priv.sizeof))
            return FALSE;

    return ret;
}

private Bool msSharePixmapBacking(PixmapPtr ppix, ScreenPtr secondary, void** handle)
{
static if (GLAMOR) {
    modesettingPtr ms = mixin(modesettingPTR!("xf86ScreenToScrn(ppix.drawable.pScreen)"));
    int ret = void;
    CARD16 stride = void;
    CARD32 size = void;
    ret = ms.glamor.shareable_fd_from_pixmap(ppix.drawable.pScreen, ppix,
                                              &stride, &size);
    if (ret == -1)
        return FALSE;

    *handle = cast(void*)cast(c_long)(ret);
    return TRUE;
}
    return FALSE;
}

private Bool msSetSharedPixmapBacking(PixmapPtr ppix, void* fd_handle)
{
static if (GLAMOR) {
    ScreenPtr screen = ppix.drawable.pScreen;
    ScrnInfoPtr scrn = xf86ScreenToScrn(screen);
    modesettingPtr ms = mixin(modesettingPTR!("scrn"));
    Bool ret = void;
    int ihandle = cast(int) cast(c_long) fd_handle;

    if (ihandle == -1)
        if (!ms.drmmode.reverse_prime_offload_mode)
           return drmmode_SetSlaveBO(ppix, &ms.drmmode, ihandle, 0, 0);

    if (ms.drmmode.reverse_prime_offload_mode) {
        ret = ms.glamor.back_pixmap_from_fd(ppix, ihandle,
                                             ppix.drawable.width,
                                             ppix.drawable.height,
                                             cast(ushort)ppix.devKind,
                                             ppix.drawable.depth,
                                             ppix.drawable.bitsPerPixel);
        if (ihandle != -1) {
            close(ihandle);
        }
    } else {
        int size = ppix.devKind * ppix.drawable.height;
        ret = drmmode_SetSlaveBO(ppix, &ms.drmmode, ihandle, ppix.devKind, size);
    }

    return ret;
} else {
    return FALSE;
}
}

private Bool msRequestSharedPixmapNotifyDamage(PixmapPtr ppix)
{
    ScreenPtr screen = ppix.drawable.pScreen;
    ScrnInfoPtr scrn = xf86ScreenToScrn(screen);
    modesettingPtr ms = mixin(modesettingPTR!("scrn"));

    msPixmapPrivPtr ppriv = mixin(msGetPixmapPriv!("&ms.drmmode", "ppix.primary_pixmap"));

    ppriv.notify_on_damage = TRUE;

    return TRUE;
}

private Bool msSharedPixmapNotifyDamage(PixmapPtr ppix)
{
    Bool ret = FALSE;
    int c = void;

    ScreenPtr screen = ppix.drawable.pScreen;
    ScrnInfoPtr scrn = xf86ScreenToScrn(screen);
    modesettingPtr ms = mixin(modesettingPTR!("scrn"));
    xf86CrtcConfigPtr xf86_config = mixin(XF86_CRTC_CONFIG_PTR!("scrn"));

    msPixmapPrivPtr ppriv = mixin(msGetPixmapPriv!("&ms.drmmode", "ppix"));

    if (!ppriv.wait_for_damage)
        return ret;
    ppriv.wait_for_damage = FALSE;

    for (c = 0; c < xf86_config.num_crtc; c++) {
        xf86CrtcPtr crtc = xf86_config.crtc[c];
        drmmode_crtc_private_ptr drmmode_crtc = cast(drmmode_crtc_private_ptr )crtc.driver_private;

        if (!drmmode_crtc)
            continue;
        if (!(drmmode_crtc.prime_pixmap && drmmode_crtc.prime_pixmap_back))
            continue;

        // Received damage on primary screen pixmap, schedule present on vblank
        ret |= drmmode_SharedPixmapPresentOnVBlank(ppix, crtc, &ms.drmmode);
    }

    return ret;
}

private Bool SetMaster(ScrnInfoPtr pScrn)
{
    modesettingPtr ms = mixin(modesettingPTR!("pScrn"));
    int ret = void;

version (XF86_PDEV_SERVER_FD) {
    if (ms.pEnt.location.type == BUS_PLATFORM &&
        (ms.pEnt.location.id.plat.flags & XF86_PDEV_SERVER_FD))
        return TRUE;
}

    if (ms.fd_passed)
        return TRUE;

    ret = drmSetMaster(ms.fd);
    if (ret)
        xf86DrvMsg(pScrn.scrnIndex, X_ERROR, "drmSetMaster failed: %s\n",
                   strerror(errno));

    return ret == 0;
}

/* When the root window is created, initialize the screen contents from
 * console if -background none was specified on the command line
 */
private Bool CreateWindow_oneshot(WindowPtr pWin)
{
    ScreenPtr pScreen = pWin.drawable.pScreen;
    ScrnInfoPtr pScrn = xf86ScreenToScrn(pScreen);
    modesettingPtr ms = mixin(modesettingPTR!("pScrn"));
    Bool ret = void;

    pScreen.CreateWindow = ms.CreateWindow;
    ret = pScreen.CreateWindow(pWin);

    if (ret)
        drmmode_copy_fb(pScrn, &ms.drmmode);
    return ret;
}

/**
 * Driver names are taken from https://drmdb.emersion.fr/drivers
 */
private int modesetting_get_cursor_interleave(int fd)
{
    drmVersionPtr version_ = drmGetVersion(fd);
    int ret = HARDWARE_CURSOR_SOURCE_MASK_NOT_INTERLEAVED;
    if (version_ is null || version_.name is null) {
        /* no operation */
    } else if (strstr(version_.name, "gma500") ||
               strstr(version_.name, "i915") ||
               strstr(version_.name, "xe")) {
        /* from xf86-video-intel */
        ret = HARDWARE_CURSOR_SOURCE_MASK_INTERLEAVE_64;
    } else if (strstr(version_.name, "nouveau") ||
               strstr(version_.name, "nvidia-drm") ||
               strstr(version_.name, "tegra")) {
        /* from xf86-video-{nouveau,nv} */
        ret =  HARDWARE_CURSOR_SOURCE_MASK_INTERLEAVE_32;
    } else if (strstr(version_.name, "amdgpu")) {
        /* from xf86-video-{amdgpu,ati} */
        ret = HARDWARE_CURSOR_SOURCE_MASK_INTERLEAVE_1;
    }

    if (version_) {
        drmFreeVersion(version_);
    }
    return ret;
}

private gbm_device* gbm_create_device_by_name(int fd, const(char)* name)
{
    gbm_device* ret = null;
    const(char)* old_backend = getenv("GBM_BACKEND");
    setenv("GBM_BACKEND", name, 1);
    ret = gbm_create_device(fd);
    unsetenv("GBM_BACKEND");
    if (old_backend) {
        setenv("GBM_BACKEND", old_backend, 1);
    }
    return ret;
}

private Bool ScreenInit(ScreenPtr pScreen, int argc, char** argv)
{
    ScrnInfoPtr pScrn = xf86ScreenToScrn(pScreen);
    modesettingPtr ms = mixin(modesettingPTR!("pScrn"));
    VisualPtr visual = void;

    pScrn.pScreen = pScreen;

    if (!SetMaster(pScrn))
        return FALSE;

static if (GLAMOR) {
    if (ms.drmmode.glamor) {
        ms.drmmode.glamor_gbm_device = TRUE;
        ms.drmmode.gbm = ms.glamor.egl_get_gbm_device(pScreen);
    }
}
    if (!ms.drmmode.gbm) {
        ms.drmmode.glamor_gbm_device = FALSE;
        ms.drmmode.gbm = gbm_create_device(ms.drmmode.fd);
        if (!ms.drmmode.gbm) {
            ms.drmmode.gbm = gbm_create_device_by_name(ms.drmmode.fd, "dumb");
        }
    }

    if (!ms.drmmode.gbm) {
        return FALSE;
    }

    /* HW dependent - FIXME */
    pScrn.displayWidth = pScrn.virtualX;
    if (!drmmode_create_initial_bos(pScrn, &ms.drmmode))
        return FALSE;

    if (ms.drmmode.shadow_enable) {
        ms.drmmode.shadow_fb =
            calloc(1,
                   pScrn.displayWidth * pScrn.virtualY *
                   ((pScrn.bitsPerPixel + 7) >> 3));
        if (!ms.drmmode.shadow_fb)
            ms.drmmode.shadow_enable = FALSE;
    }

    miClearVisualTypes();

    if (!miSetVisualTypes(pScrn.depth,
                          miGetDefaultVisualMask(pScrn.depth),
                          pScrn.rgbBits, pScrn.defaultVisual))
        return FALSE;

    if (!miSetPixmapDepths())
        return FALSE;

    if (!dixRegisterScreenSpecificPrivateKey
        (pScreen, &ms.drmmode.pixmapPrivateKeyRec, PRIVATE_PIXMAP,
         msPixmapPrivRec.sizeof)) {
        return FALSE;
    }

    pScrn.memPhysBase = 0;
    pScrn.fbOffset = 0;

    if (!fbScreenInit(pScreen, null,
                      pScrn.virtualX, pScrn.virtualY,
                      pScrn.xDpi, pScrn.yDpi,
                      pScrn.displayWidth, pScrn.bitsPerPixel))
        return FALSE;

    if (pScrn.bitsPerPixel > 8) {
        /* Fixup RGB ordering */
        visual = pScreen.visuals + pScreen.numVisuals;
        while (--visual >= pScreen.visuals) {
            if ((visual.class_ | DynamicClass) == DirectColor) {
                visual.offsetRed = cast(int)pScrn.offset.red;
                visual.offsetGreen = cast(int)pScrn.offset.green;
                visual.offsetBlue = cast(int)pScrn.offset.blue;
                visual.redMask = pScrn.mask.red;
                visual.greenMask = pScrn.mask.green;
                visual.blueMask = pScrn.mask.blue;
            }
        }
    }

    fbPictureInit(pScreen, null, 0);

    if (drmmode_init(pScrn, &ms.drmmode) == FALSE) {
        xf86DrvMsg(pScrn.scrnIndex, X_ERROR,
                   "Failed to initialize glamor at ScreenInit() time.\n");
        return FALSE;
    }

    if (ms.drmmode.shadow_enable && !ms.shadow.Setup(pScreen)) {
        xf86DrvMsg(pScrn.scrnIndex, X_ERROR, "shadow fb init failed\n");
        return FALSE;
    }

    pScreen.CreateScreenResources = &modesetCreateScreenResources;

    xf86SetBlackWhitePixels(pScreen);

    xf86SetBackingStore(pScreen);
    xf86SetSilkenMouse(pScreen);
    miDCInitialize(pScreen, cast(_miPointerScreenFuncRec*)xf86GetPointerScreenFuncs());

    /* If pageflip is enabled hook the screen's cursor-sprite (swcursor) funcs.
     * So that we can disable page-flipping on fallback to a swcursor. */
    if (ms.drmmode.pageflip) {
        miPointerScreenPtr PointPriv = cast(_MiPointerScreenRec*)dixLookupPrivate(&pScreen.devPrivates, miPointerScreenKey);

        if (!dixRegisterScreenPrivateKey(&ms.drmmode.spritePrivateKeyRec,
                                         pScreen, PRIVATE_DEVICE,
                                         msSpritePrivRec.sizeof))
            return FALSE;

        ms.SpriteFuncs = PointPriv.spriteFuncs;
        PointPriv.spriteFuncs = &drmmode_sprite_funcs;
    }

    /* Need to extend HWcursor support to handle mask interleave */
    if (!ms.drmmode.sw_cursor) {
        /* XXX Is there any spec that says we should interleave the cursor bits? XXX */
        int interleave = modesetting_get_cursor_interleave(ms.drmmode.fd);

        xf86_cursors_init(pScreen, ms.cursor_image_width, ms.cursor_image_height,
                          interleave |
                          HARDWARE_CURSOR_UPDATE_UNHIDDEN |
                          HARDWARE_CURSOR_ARGB);
    }

    /* Must force it before EnterVT, so we are in control of VT and
     * later memory should be bound when allocating, e.g rotate_mem */
    pScrn.vtSema = TRUE;

    if (serverGeneration == 1 && bgNoneRoot && ms.drmmode.glamor_gbm) {
        ms.CreateWindow = pScreen.CreateWindow;
        pScreen.CreateWindow = &CreateWindow_oneshot;
    }

    pScreen.SaveScreen = &xf86SaveScreen;
    ms.CloseScreen = pScreen.CloseScreen;
    pScreen.CloseScreen = &CloseScreen;

    ms.BlockHandler = pScreen.BlockHandler;
    pScreen.BlockHandler = &msBlockHandler_oneshot;

    pScreen.SharePixmapBacking = &msSharePixmapBacking;
    pScreen.SetSharedPixmapBacking = &msSetSharedPixmapBacking;
    pScreen.StartPixmapTracking = &PixmapStartDirtyTracking;
    pScreen.StopPixmapTracking = &PixmapStopDirtyTracking;

    pScreen.SharedPixmapNotifyDamage = &msSharedPixmapNotifyDamage;
    pScreen.RequestSharedPixmapNotifyDamage = 
        &msRequestSharedPixmapNotifyDamage;

    pScreen.PresentSharedPixmap = &msPresentSharedPixmap;
    pScreen.StopFlippingPixmapTracking = &msStopFlippingPixmapTracking;

    if (!xf86CrtcScreenInit(pScreen))
        return FALSE;

    if (!drmmode_setup_colormap(pScreen, pScrn))
        return FALSE;

    if (ms.atomic_modeset)
        xf86DPMSInit(pScreen, &drmmode_set_dpms, 0);
    else
        xf86DPMSInit(pScreen, &xf86DPMSSet, 0);

static if (HasVersion!"GLAMOR" && HasVersion!"XV") {
    if (ms.drmmode.glamor) {
        XF86VideoAdaptorPtr glamor_adaptor = void;

        glamor_adaptor = ms.glamor.xv_init(pScreen, 16);
        if (glamor_adaptor !is null)
            xf86XVScreenInit(pScreen, &glamor_adaptor, 1);
        else
            xf86DrvMsg(pScrn.scrnIndex, X_ERROR,
                       "Failed to initialize XV support.\n");
    }
}

    if (serverGeneration == 1)
        xf86ShowUnusedOptions(pScrn.scrnIndex, cast(_InputOption*)pScrn.options);

    if (!ms_vblank_screen_init(pScreen)) {
        xf86DrvMsg(pScrn.scrnIndex, X_ERROR,
                   "Failed to initialize vblank support.\n");
        return FALSE;
    }

static if (GLAMOR) {
    if (ms.drmmode.glamor_gbm) {
        if (((ms.drmmode.dri2_enable = ms_dri2_screen_init(pScreen)) == 0)) {
            xf86DrvMsg(pScrn.scrnIndex, X_ERROR,
                       "Failed to initialize the DRI2 extension.\n");
        }

        /* enable reverse prime if we are a GPU screen, and accelerated, and not
         * i915, evdi or udl. i915 is happy scanning out from sysmem.
         * evdi and udl are virtual drivers scanning out from sysmem
         * backed dumb buffers.
         */
        if (pScreen.isGPU) {
            drmVersionPtr version_ = void;

            /* enable if we are an accelerated GPU screen */
            ms.drmmode.reverse_prime_offload_mode = TRUE;

            if ((version_ = drmGetVersion(ms.drmmode.fd)) != null) {
                if (!strncmp("i915", version_.name, version_.name_len)) {
                    ms.drmmode.reverse_prime_offload_mode = FALSE;
                }
                if (!strncmp("evdi", version_.name, version_.name_len)) {
                    ms.drmmode.reverse_prime_offload_mode = FALSE;
                }
                if (!strncmp("udl", version_.name, version_.name_len)) {
                    ms.drmmode.reverse_prime_offload_mode = FALSE;
                }
                if (!ms.drmmode.reverse_prime_offload_mode) {
                    xf86DrvMsg(pScrn.scrnIndex, X_INFO,
                       "Disable reverse prime offload mode for %s.\n", version_.name);
                } else {
                    xf86DrvMsg(pScrn.scrnIndex, X_INFO,
                       "Enable reverse prime offload mode for %s.\n", version_.name);
                }
                drmFreeVersion(version_);
            } else {
                xf86DrvMsg(pScrn.scrnIndex, X_INFO,
                           "Reverse prime offload mode enabled.\n");
            }
        }
    }
}
    if (((ms.drmmode.present_enable = ms_present_screen_init(pScreen)) == 0)) {
        xf86DrvMsg(pScrn.scrnIndex, X_ERROR,
                   "Failed to initialize the Present extension.\n");
    }


    pScrn.vtSema = TRUE;

    if (ms.vrr_support)
        pScreen.SetWindowVRRMode = &msSetWindowVRRMode;

    return TRUE;
}

private void AdjustFrame(ScrnInfoPtr pScrn, int x, int y)
{
    modesettingPtr ms = mixin(modesettingPTR!("pScrn"));

    drmmode_adjust_frame(pScrn, &ms.drmmode, x, y);
}

private void LeaveVT(ScrnInfoPtr pScrn)
{
    modesettingPtr ms = mixin(modesettingPTR!("pScrn"));

    xf86_hide_cursors(pScrn);

    pScrn.vtSema = FALSE;

version (XF86_PDEV_SERVER_FD) {
    if (ms.pEnt.location.type == BUS_PLATFORM &&
        (ms.pEnt.location.id.plat.flags & XF86_PDEV_SERVER_FD))
        return;
}

    if (!ms.fd_passed)
        drmDropMaster(ms.fd);
}

/*
 * This gets called when gaining control of the VT, and from ScreenInit().
 */
private Bool EnterVT(ScrnInfoPtr pScrn)
{
    modesettingPtr ms = mixin(modesettingPTR!("pScrn"));

    pScrn.vtSema = TRUE;

    SetMaster(pScrn);

    drmmode_update_kms_state(&ms.drmmode);

    /* allow not all modes to be set successfully since some events might have
     * happened while not being master that could prevent the previous
     * configuration from being re-applied.
     */
    if (!drmmode_set_desired_modes(pScrn, &ms.drmmode, TRUE, TRUE)) {
        xf86DisableUnusedFunctions(pScrn);

        /* TODO: check that at least one screen is on, to allow the user to fix
         * their setup if all modeset failed...
         */

        /* Tell the desktop environment that something changed, so that they
         * can hopefully correct the situation
         */
        RRSetChanged(xf86ScrnToScreen(pScrn));
        RRTellChanged(xf86ScrnToScreen(pScrn));
    }

    return TRUE;
}

private Bool SwitchMode(ScrnInfoPtr pScrn, DisplayModePtr mode)
{
    return xf86SetSingleMode(pScrn, mode, RR_Rotate_0);
}

private Bool CloseScreen(ScreenPtr pScreen)
{
    ScrnInfoPtr pScrn = xf86ScreenToScrn(pScreen);
    modesettingPtr ms = mixin(modesettingPTR!("pScrn"));
    modesettingEntPtr ms_ent = ms_ent_priv(pScrn);

    /* Clear mask of assigned crtc's in this generation */
    ms_ent.assigned_crtcs = 0;

static if (GLAMOR) {
    if (ms.drmmode.dri2_enable) {
        ms_dri2_close_screen(pScreen);
    }
}

    ms_vblank_close_screen(pScreen);

    if (ms.damage) {
        DamageUnregister(ms.damage);
        DamageDestroy(ms.damage);
        ms.damage = null;
    }

    if (ms.drmmode.shadow_enable) {
        ms.shadow.Remove(pScreen, pScreen.GetScreenPixmap(pScreen));
        free(ms.drmmode.shadow_fb);
        ms.drmmode.shadow_fb = null;
        free(ms.drmmode.shadow_fb2);
        ms.drmmode.shadow_fb2 = null;
    }

    if (!ms.drmmode.sw_cursor || ms.drmmode.set_cursor_failed) {
        xf86_cursors_fini(pScreen);
    }

    drmmode_uevent_fini(pScrn, &ms.drmmode);

    drmmode_free_bos(pScrn, &ms.drmmode);

static if (GLAMOR) {
    /* If we didn't get the gbm device from glamor, we have to free it ourserves */
    if (!ms.drmmode.glamor_gbm_device)
    {
        gbm_device_destroy(ms.drmmode.gbm);
        ms.drmmode.gbm = null;
    }
}
else {
    if (!ms.drmmode.glamor_gbm_device)
    {
        gbm_device_destroy(ms.drmmode.gbm);
        ms.drmmode.gbm = null;
    }
}

    if (ms.drmmode.pageflip) {
        miPointerScreenPtr PointPriv = cast(_MiPointerScreenRec*)dixLookupPrivate(&pScreen.devPrivates, miPointerScreenKey);

        if (PointPriv.spriteFuncs == &drmmode_sprite_funcs)
            PointPriv.spriteFuncs = ms.SpriteFuncs;
    }

    if (pScrn.vtSema) {
        LeaveVT(pScrn);
    }

    pScreen.BlockHandler = ms.BlockHandler;

    pScrn.vtSema = FALSE;
    pScreen.CloseScreen = ms.CloseScreen;
    return (*pScreen.CloseScreen) (pScreen);
}

private ModeStatus ValidMode(ScrnInfoPtr arg, DisplayModePtr mode, Bool verbose, int flags)
{
    return MODE_OK;
}
